### ISSUE TITLE
How to build/use this?

### ISSUE THREAD

**Issue by hashhashhash** [Profpatsch/yarn2nix#1]
I like that you  have git support, which I assume also includes "git+ssh" support. Can you document how to make it run? You are for example also referring to a package.nix file, which doesn't exist in the repository. 

You also haven't documented the specific dependencies. <nixpkgs> is a moving target, from what I understand.

**Comment by Profpatsch** [comment]
I’m still working on it, yes. The conversion (and git-fetching) parts already work, the parser fails for some especially egregious cases sometimes. The big part that’s still missing is a good integration into nixpkgs. I have been experimenting with that, but haven’t found the time recently.

I have a concrete work project where I’m going to use it soon, so that’s where I’ll release the first version.

**Comment by Profpatsch** [comment]
I added a [README](https://github.com/Profpatsch/yarn2nix#readme) now, please try it out and tell me about the results! Would be interested whether the tool works for you.

**Comment by Profpatsch** [comment]
I’m closing this issue, do not hesitate to open an issue if you have problems getting `yarn2nix` to run.
